[package]
name = "pyscol"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true

[lib]
name = "pyscol"
crate-type = ["cdylib"]

[features]
gdcm = ["labelme-rs/gdcm"]

[dependencies]
env_logger.workspace = true
numpy = "0.26.0"
pyo3 = { version = "0.26.0", features = ["extension-module"] }
scolrs = { path = "../scolrs" }
devsc = { path = "../devsc" }
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# getrandom = { features = ["js"] } # for ndarray-stats
clahe = { path = "clahe" }
# clahe = { git = "https://github.com/ykszk/clahe.git", branch="develop" }
serde.workspace = true
serde_json.workspace = true
svg.workspace = true
thiserror.workspace = true
log.workspace = true
labelme-rs.workspace = true

[dev-dependencies]
walkdir = "2.4.0"
