[workspace]
members = [
    "crates/scolrs",
    "crates/commands",
    "crates/pyscol",
    "crates/devsc",
    "crates/named_derive",
    "crates/deepscol",
    "crates/deepscol_wasm",
]
default-members = ["crates/scolrs", "crates/commands"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]
repository = "https://github.com/ykszk/scolrs"
description = "Analyze spinal deformity in radiographs"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
env_logger = "0.11.8"
log = "0.4.29"
ndarray = "0.16"                                                                                            # ndarray-stats requires 0.16
ndarray-stats = "0.6"
pretty_assertions = "1.4.1"
serde = "1.0.228"
svg = "0.18.0"
thiserror = "2.0"
labelme-rs = { git = "https://github.com/ykszk/labelme-rs.git", tag = "v0.13.5", default-features = false }
scraper = { version = "0.25.0", default-features = false }
tera = { version = "1.20", default-features = false }
indexmap = "2.12.1"
serde_json = "1.0.146"
config = { version = "0.15.19", default-features = false, features = ["toml"] }
dicom-core = { version = "0.9.0" }
dicom-object = { version = "0.9.0" }

[profile.release-z]
inherits = "release"
strip = true
opt-level = "z"      # Optimize for size
lto = true
codegen-units = 1
