[package]
name = "scolrs"
version = "0.1.0"
edition = "2021"

authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]

[[bin]]
name = "scolrs"
path = "src/main.rs"

[lib]
name = "scolrs"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10.0"
labelme-rs = { git = "https://github.com/ykszk/labelme-rs.git" }
log = "0.4.20"
lyon_geom = "1.0.4"
mimalloc = "0.1.39"
ndarray = "0.15"
serde = "1.0.188"
svg = "0.14"
thiserror = "1.0"
toml = "0.8.2"
