[workspace]
members = ["crates/scolrs", "crates/pyscol"]
default-members = ["crates/scolrs"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]
repository = "https://github.com/ykszk/scolrs"
description = "Adolescent Idiopathic Scoliosis"
