[package]
name = "deepscol_wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lib]
crate-type = ["cdylib"]
name = "deepscol"
path = "src/lib.rs"

[dependencies]
scolrs = { path = "../scolrs" }
deepscol = { path = "../deepscol", default-features = false, features = [
    "wasm",
] }

anyhow.workspace = true
labelme-rs.workspace = true
log.workspace = true
ndarray.workspace = true
config.workspace = true
env_logger.workspace = true
ndarray-stats.workspace = true
serde.workspace = true
serde_json.workspace = true

console_error_panic_hook = "0.1.7"
js-sys = "0.3.83"
wasm-bindgen = "0.2.106"
wasm-logger = "0.2.0"
wee_alloc = "0.4.5"

[build-dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
reqwest = { version = "0.12.22", features = ["blocking"] }
