[package]
name = "scolrs-commands"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "scolrs"
path = "src/main.rs"

[features]
dicom = ["labelme-rs/dicom"]
gdcm = ["dicom", "labelme-rs/gdcm"]

[dependencies]
named_derive = { path = "../named_derive" }
scolrs = { path = "../scolrs", features = ["webp"] }

toml = "0.9.8"
glob = "0.3.3"
clap_complete = "4.5.60"
tar = "0.4"
rayon = "1.11.0"
ndarray-npz = { version = "0.4.2", default-features = false, features = ["compressed"]}
ndarray-ndimage = "0.5.0"
config = { version = "0.15.19", default-features = false, features = ["toml"] }

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
indexmap.workspace = true
labelme-rs.workspace = true
log.workspace = true
ndarray.workspace = true
ndarray-stats.workspace = true
serde.workspace = true
svg.workspace = true
thiserror.workspace = true
scraper.workspace = true
tera.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd = "2.0.16"
float-cmp = "0.10.0"
rstest = "0.26.1"
