[package]
name = "scolrs-commands"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[[bin]]
name = "scolrs"
path = "src/main.rs"

[features]
dicom = ["labelme-rs/dicom"]
gdcm = ["dicom", "labelme-rs/gdcm"]

[dependencies]
scolrs = { path = "../scolrs", features = ["webp"] }

toml = "0.9.8"
glob = "0.3.3"
clap_complete = "4.5.62"
tar = "0.4"
rayon = "1.11.0"
metaimage = { git = "https://github.com/ykszk/metaimage-rs.git", tag = "v0.1.2"}

anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
indexmap.workspace = true
labelme-rs.workspace = true
log.workspace = true
ndarray.workspace = true
ndarray-stats.workspace = true
serde.workspace = true
svg.workspace = true
thiserror.workspace = true
scraper.workspace = true
tera.workspace = true
serde_json.workspace = true
config.workspace = true
csv.workspace = true
clap_mangen = "0.2.31"

[dev-dependencies]
assert_cmd = "2.1.1"
float-cmp = "0.10.0"
rstest = "0.26.1"
