[package]
name = "scolrs"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true

[lib]
name = "scolrs"
path = "src/lib.rs"

[features]
dicom = ["labelme-rs/dicom"]
gdcm = ["dicom", "labelme-rs/gdcm"]
webp = ["dep:webp"]

[dependencies]
named_derive = { path = "../named_derive" }
csv.workspace = true
dicom-core.workspace = true
dicom-object.workspace = true
dicom-dictionary-std = { version = "0.9.0" }
lyon_geom = "1.0.18"
rulinalg = "0.4.2"                                          # replace with nalgebra?
serde_repr = "0.1.20"
strum = { version = "0.27.2", features = ["derive"] }
regex = "1.12.2"
base64 = "0.22.1"
webp = { version = "0.3.1", optional = true }
shadow-rs = { version = "1.5.0", default-features = false }
ndarray-ndimage = "0.5.0"

clap.workspace = true
env_logger.workspace = true
indexmap.workspace = true
labelme-rs.workspace = true
log.workspace = true
ndarray.workspace = true
ndarray-stats.workspace = true
serde.workspace = true
serde_json.workspace = true
svg.workspace = true
thiserror.workspace = true
scraper.workspace = true
tera = { workspace = true, features = ["urlencode"] }
config.workspace = true
serde_yaml = "0.9.34"

[dev-dependencies]
anyhow.workspace = true
pretty_assertions.workspace = true

[build-dependencies]
shadow-rs = "1.4.0"
