[package]
name = "deepscol"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true


[lib]
name = "deepscol"
path = "src/lib.rs"

[[bin]]
name = "deepscol"
path = "src/main.rs"

[[bin]]
name = "dev"
path = "src/dev.rs"

[features]
default = ["std"]
std = ["ort/std", "ort/download-binaries"]
wasm = ["ort/alternative-backend"]

[dependencies]
scolrs = { path = "../scolrs", features = ['dicom'] }

serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
config.workspace = true
env_logger.workspace = true
clap.workspace = true
labelme-rs.workspace = true
log.workspace = true
ndarray.workspace = true
ndarray-stats.workspace = true

dicom-object.workspace = true
dicom-pixeldata = { version = "0.9.0", default-features = false, features = [
    "native",
    "image",
] }
image = { version = "0.25.9", default-features = false, features = [
    "jpeg",
    "png",
    "tiff",
] }
imageproc = "0.25.0"
ndarray-npz = { version = "0.4.2", default-features = false, features = [
    "compressed",
] }
ort = { version = "2.0.0-rc.10", default-features = false, features = [
    "ndarray",
] }
tracing-subscriber = "0.3.22"
wasm-bindgen = "0.2.106"

[build-dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
reqwest = { version = "0.12.26", features = ["blocking"] }
