[package]
name = "devsc"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[lib]
name = "devscol"
crate-type = ["lib"]

[dependencies]
env_logger.workspace = true
log.workspace = true
ndarray.workspace = true
ndarray-ndimage = "0.4.0"
ndarray-stats = "0.6.0"
scolrs = { path = "../scolrs" }
serde.workspace = true
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# getrandom = { features = ["js"] } # for ndarray-stats

[dev-dependencies]
anyhow.workspace = true
pretty_assertions.workspace = true
walkdir = "2.4.0"
dicom = "0.7.1"
dicom-pixeldata = { version = "0.7.1", default-features = false, features = [
    "native",
    "image",
    "ndarray",
    # "gdcm",
] }
dicom-transfer-syntax-registry = { version = "0.7.1" }
